"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tmrm = require("azure-pipelines-task-lib/mock-run");
const path = require("path");
let taskPath = path.join(__dirname, '..', 'index.js');
let tmr = new tmrm.TaskMockRunner(taskPath);
tmr.setInput('organization', 'curo');
tmr.setInput('pullRequestId', '1');
tmr.setInput('pat', 'blah');
tmr.setInput('field', 'curo');
tmr.run();
